### ISSUE TITLE
error running mrt on newly created meteor app

### ISSUE THREAD

**Issue by batewtew** [oortcloud/meteorite#128]
I ran into this error twice, one was after installing nodejs (from package) and meteorite, then second was after compiling nodejs and installing meteorite.

Also posted it here:
https://groups.google.com/forum/?fromgroups=#!searchin/meteor-talk/%5Bmeteorite%5D/meteor-talk/zDno8__hJR0/P1D-5bCHNDQJ

Machine is CentOS release 6.3 (Final)

```

[eweb@lxmv40 microscope]$ mrt

Stand back while Meteorite does its thing

Installing Meteor

  branch: https://github.com/meteor/meteor.git#master

Installing smart packages

Adding meteorite to .meteor/gitignore

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

[[[[[ ~/meteor_stuff/microscope ]]]]]

livedata: updating npm dependencies -- sockjs, websocket...
No dependency info in bundle. Filesystem monitoring disabled.
=> Errors prevented startup:
Exception while bundling application:
Error: Can't install npm dependencies. Check your internet connection and try again.
    at Object._.extend._ensureConnected (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/meteor_npm.js:361:13)
    at Object._.extend._installFromShrinkwrap (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/meteor_npm.js:347:10)
    at Object._.extend._updateExistingNpmDirectory (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/meteor_npm.js:158:12)
    at Object._.extend.updateDependencies (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/meteor_npm.js:81:14)
    at _.extend.installNpmDependencies (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/packages.js:311:17)
    at _.extend._maybeUpdateNpmDependencies (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/bundler.js:408:13)
    at _.extend.use (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/bundler.js:447:10)
    at self.api.use (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/bundler.js:114:21)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.self.api.use (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/bundler.js:110:9)
    at _.extend.init_from_app_dir [as on_use_handler] (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/packages.js:232:11)
    at _.extend.use (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/bundler.js:450:11)
    at Object.exports.bundle (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/bundler.js:859:12)
    at /home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/run.js:694:26
    at exports.inFiber (/home/eweb/.meteorite/meteors/meteor/meteor/bfe4b72ebec4367eaddcdf0887fcf5e649d9dcb8/tools/fiber-helpers.js:24:12)

Please fix the problem and restart.
[eweb@lxmv40 microscope]$ 
```

**Comment by marlontamo** [comment]
![error](https://user-images.githubusercontent.com/11057114/27322060-36283cfc-55cf-11e7-8d2d-fcf0b2e73042.PNG)
im new  here and im trying to install meteorite but im having issues installing it :)

**Comment by dburles** [comment]
Hey @marlontamo are you working on a new Meteor app? If so, you won't need meteorite! It was replaced 3 years ago with Meteor's own packaging system

**Comment by marlontamo** [comment]
oh thanks sir@dburles do you have  idea on how can I integrate meteor and phonegap? do you have any link that could help? thanksss...

**Comment by dburles** [comment]
@marlontamo the Meteor guide is what you're after. https://guide.meteor.com. Also see the section on mobile https://guide.meteor.com/mobile.html
