### ISSUE TITLE
(Windows) -  'sh' is not recognized.

### ISSUE THREAD

**Issue by shahzadns** [oortcloud/meteorite#307]
Hi, I am a Windows User wind8.1 64bit , i followed the instruction from [StackOverFlow Post](http://stackoverflow.com/questions/20949780/how-to-install-meteorite-for-windows?answertab=active#tab-top) (that answer which is referring here) but getting errors on npm install.

I cloned the repo (tried both <code>master</code> and <code>windows-updates</code> branch) to C:\Users\User\AppData\Roaming\npm\node_modules
and then <code>cd meteorite </code> then <code>npm install</code> 
it gives an error
<code> 'sh' is not recognized as an internal or external command, operable program or batch file.</code> 

Can you help in that ?
Thanks so much!

**Comment by kuncevic** [comment]
Got same thing on same windows version.

I was managed to finally install `meteorite` on windows using `cygwin` https://cygwin.com/install.html: 

![image](https://cloud.githubusercontent.com/assets/1283734/11359803/935a1960-92d3-11e5-8782-c9abb39afccd.png)

...but finally end up with another error wen was just trying to run it.

 `npm install -g meteorite` running well with cygwin `bash`

Then I've got the below popup once typed `mrt` in console because I have`Microsoft Windows Malicious Software Removal Tool` installed in the system.
![image](https://cloud.githubusercontent.com/assets/1283734/11360035/364d4f10-92d5-11e5-9767-f4d787f625ff.png)

After I removed `mrt.exe` from `%windir%\system32\` I can run the meteorite by typing `mrt` but getting an error:
Using windows `cmd` I've got this error:

```
d:\Projects\meteor\test-cordova>mrt add cordova-loader
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Function.Meteorite.root (C:\Users\User1\AppData\Roaming\npm\node_modules\m
eteorite\lib\meteorite.js:253:15)
    at Function.Meteorite.prepareFS (C:\Users\User1\AppData\Roaming\npm\node_modu
les\meteorite\lib\meteorite.js:258:24)
    at new Meteorite (C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\l
ib\meteorite.js:20:13)
    at Object.<anonymous> (C:\Users\User1\AppData\Roaming\npm\node_modules\meteor
ite\bin\mrt.js:15:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

By running `mrt` in cygwin `bash` I've got this error:

```
User1@PC /cygdrive/d/Projects/Learning/meteor/test-cordova
$ mrt add cordova-loader
✓ cordova-loader
    tag: https://github.com/andrewreedy/cordova-loader.git#v0.1.0
fs.js:945
  return binding.symlink(preprocessSymlinkDestination(destination, type, path),
                 ^

Error: EISDIR: illegal operation on a directory, symlink 'C:\cygwin64\home\User1\.meteorite\packages\cordova-loader\andrewreedy\cordova-loader\1237a90ed21f4e419b4699b6be543dd128352586' -> 'D:\Projects\Learning\meteor\test-cordova\packages\cordova-loader'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\lib\dependencies\package.js:129:10
    at C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\lib\sources\git.js:84:15
    at GitSource._load (C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\lib\sources\git.js:141:12)
    at C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\lib\sources\git.js:82:18
    at C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\lib\sources\git.js:98:5
    at C:\Users\User1\AppData\Roaming\npm\node_modules\meteorite\lib\sources\git.js:263:5
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:92:20)
```

Also getting same errors if I just type `mrt run`

It is might be looking like similar issue here https://github.com/oortcloud/meteorite/issues/32 but I didn't manage to resolve this one yet.

**Comment by dburles** [comment]
@riapp looking at the errors, you seem to be working with Meteor in a very out of date approach. Meteor has had packaging and cordova support for quite some time now. Take a look at `meteor help add` and `meteor help add-platform`.

**Comment by kuncevic** [comment]
@dburles I was just trying to make `mrt` working on my Windows machine. Is `mrt` sort of outdated? Is `meteor add` is kind of replacement to `mrt`?
