### ISSUE TITLE
Error: Cannot find module 'exec-sync'

### ISSUE THREAD

**Issue by hokster7** [oortcloud/meteorite#84]
Reproduction:

```
sudo npm install -g meteor
sudo npm install -g meteorite
sudo npm install -g exec-sync
sudo npm install -g execSync
mrt create newproj
cd newproj
mrt add typescript
mrt add router
```

Optionally

```
sudo npm link exec-sync
mrt add typescript
```

Stacktrace:

```
Error: Cannot find module 'exec-sync'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
...
```

The trace is shown for any attempt to `mrt add` anything after that!

Also covered by [this StackOverflow question](http://stackoverflow.com/questions/14983049/meteorite-trouble-with-exec-sync).

**Comment by rodrigopssilva** [comment]
Same problem here!
